
trigger:
  branches:
    include:
      - main

stages:
  - stage: DeployToDev
    displayName: "Deploy to Development ADF"
    jobs:
      - job: DeployADF
        displayName: "Deploy ADF Pipeline"
        pool:
          vmImage: 'windows-latest'
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'My-Azure-Service-Connection'  # Replace with your service connection name
              scriptType: 'ps'
              scriptLocation: 'scriptPath'
              scriptPath: 'ADF/Deploy-AdfPipeline.ps1'
              workingDirectory: '$(System.DefaultWorkingDirectory)'
            displayName: 'Run PowerShell Script to Deploy ADF Pipeline'

  - stage: DeployToProd
    displayName: "Deploy to Production ADF"
    dependsOn: DeployToDev
    condition: succeeded()
    approval:
      approvals:
        - approvals: manual
    jobs:
      - job: DeployProdADF
        displayName: "Deploy ADF to Prod"
        pool:
          vmImage: 'windows-latest'
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'My-Azure-Service-Connection'
              scriptType: 'ps'
              scriptLocation: 'scriptPath'
              scriptPath: 'ADF/Deploy-AdfPipeline.ps1'
              workingDirectory: '$(System.DefaultWorkingDirectory)'
            displayName: 'Deploy to Production ADF'
